name: RPGClass
version: '${project.version}'
main: com.outcast.rpgclass.RPGClass
api-version: 1.19
depend: [ RPGCore, RPGSkill ]
authors: [ Hexacorx ]
description: The class plugin that will users class data such as class level, attributes, skills, and other model information.
website: www.outcastrpg.com